services:
  web-app:
    build:
      context: .
    ports:
      - "8001:8001"
    volumes:
      - ./zapis:/zapis
    environment:
      - DB_HOST=database
      - DB_NAME=dbnamezapis
      - DB_USER=dbuserzapis
      - DB_PASS=passzapis
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8001"
    depends_on:
      - database
      - redis
      - worker

  database:
    image: postgres:16.1-alpine3.19
    environment:
      - POSTGRES_DB=dbnamezapis
      - POSTGRES_USER=dbuserzapis
      - POSTGRES_PASSWORD=passzapis

  redis:
    image: redis:7.0.5-alpine
    hostname: redis

  worker:
    build:
      context: .
    hostname: worker
    entrypoint: celery
    command: -A celery_app.app worker --loglevel=info
    volumes:
      - ./zapis:/zapis
    links:
      - redis
    depends_on:
      - redis

  flower:
    build:
      context: .
    hostname: flower
    entrypoint: celery
    command: -A celery_app.app flower
    volumes:
      - ./zapis:/zapis
    links:
      - redis
    depends_on:
      - redis
    ports:
      - "5555:5555"