services:
  web-app:
    build:
      context: .
    ports:
      - "8001:8001"
    volumes:
      - ./zapis:/zapis

    environment:
      - DB_HOST=database
      - DB_NAME=dbnamezapis
      - DB_USER=dbuserzapis
      - DB_PASS=passzapis

    command: >
      sh -c "python manage.py runserver 0.0.0.0:8001"

    depends_on:
      - database

  database:
   image: postgres:16.1-alpine3.19
   environment:
     - POSTGRES_DB=dbnamezapis
     - POSTGRES_USER=dbuserzapis
     - POSTGRES_PASSWORD=passzapis